# Generated by Django 3.2.18 on 2023-02-24 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('type', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=90)),
                ('post', models.CharField(max_length=90)),
                ('pin', models.IntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('email', models.CharField(max_length=90)),
                ('pt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.login')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('gender', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=90)),
                ('post', models.CharField(max_length=90)),
                ('pin', models.IntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('email', models.CharField(max_length=90)),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.login')),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=90)),
                ('date', models.DateField()),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials', models.CharField(max_length=90)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=90)),
                ('rating', models.CharField(max_length=90)),
                ('pt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=90)),
                ('date', models.DateField()),
                ('pt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.parent')),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=90)),
                ('date', models.DateField()),
                ('fromid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromid', to='sign.login')),
                ('toid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toid', to='sign.login')),
            ],
        ),
    ]
