# Generated by Django 3.2.18 on 2023-02-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20230225_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
